"""Generate committed OpenAPI JSON and TypeScript DTOs from the FastAPI application."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from camcat.api import app

ROOT = Path(__file__).resolve().parents[1]


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return str(schema["$ref"]).rsplit("/", 1)[-1]
    if "anyOf" in schema:
        return " | ".join(ts_type(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item, ensure_ascii=False) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "object":
        properties = schema.get("properties")
        if not properties:
            return "Record<string, unknown>"
        required = set(schema.get("required", []))
        fields = [
            f"  {json.dumps(name)}{'?' if name not in required else ''}: {ts_type(value)};"
            for name, value in properties.items()
        ]
        return "{\n" + "\n".join(fields) + "\n}"
    return "string" if kind == "string" else "unknown"


def generated_artifacts() -> dict[Path, str]:
    schema = app.openapi()
    definitions = schema.get("components", {}).get("schemas", {})
    lines = [
        "// Generated by scripts/generate_openapi_contracts.py; do not edit manually.",
        "",
    ]
    for name in sorted(definitions):
        lines.append(f"export type {name} = {ts_type(definitions[name])};")
        lines.append("")
    return {
        ROOT / "packages" / "contracts" / "openapi.json": (
            json.dumps(schema, ensure_ascii=False, indent=2) + "\n"
        ),
        ROOT / "apps" / "web" / "src" / "generated" / "api.ts": "\n".join(lines),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero when committed contracts differ from the FastAPI schema",
    )
    args = parser.parse_args(argv)
    stale: list[Path] = []
    missing: list[Path] = []
    for path, expected in generated_artifacts().items():
        if args.check:
            if not path.is_file():
                missing.append(path)
            elif path.read_text(encoding="utf-8") != expected:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8")
    if missing or stale:
        for path in missing:
            print(f"generated contract is missing: {path.relative_to(ROOT)}", file=sys.stderr)
        for path in stale:
            print(f"generated contract is stale: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
